### ISSUE TITLE
Error after import

### ISSUE THREAD

**Issue by ygxxii** [cqjjjzr/MusicBee-DesktopLyrics#1]
MusiBee Version: 3.2.6827
```
MusicBee v3.2.6827.32939 (Win10.0), 6 10月 2018 15:05:

System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBeePlugin.FrmLyrics.RenderLyrics(String lyric, Font font)
   at MusicBeePlugin.FrmLyrics.DrawLyrics1Line(String lyrics)
   at MusicBeePlugin.FrmLyrics.Redraw()
   at MusicBeePlugin.FrmLyrics.UpdateLyrics(String line1, String line2)
   at MusicBeePlugin.Plugin.<UpdateLyrics>b__198_0(String line1, String line2)
```

**Comment by cqjjjzr** [comment]
Should be fixed with recent updates. Please reopen if the problem persists and provide new logs (since the code structure has changed).
